name: whatsie
adopt-info: whatsie-build-src

grade: stable
confinement: strict
base: core24
compression: lzo

icon: snap/gui/icon.svg

platforms:
  amd64:
  arm64:

plugs:
  hunspell-dictionaries:
    content: hunspell-dictionaries
    interface: content
    target: $SNAP/usr/share/hunspell
    default-provider: hunspell-dictionaries

apps:
  whatsie:
    command: usr/bin/whatsie
    environment:
      DICPATH: $SNAP/usr/share/hunspell
    desktop: usr/share/applications/com.ktechpit.whatsie.desktop
    common-id: com.ktechpit.whatsie
    extensions:
      - kde-neon-6
    plugs:
      - home
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - network
      - unity7
      - browser-support
      - network-status
      - camera
      - audio-playback
      - audio-record
      - removable-media
      - screen-inhibit-control
      - hardware-observe
      - network-observe
      - network-bind
      - mount-observe


parts:
  whatsie-build-src:
    plugin: cmake
    source: .
    parse-info:
      - dist/linux/com.ktechpit.whatsie.appdata.xml
    build-snaps:
      - hunspell-dictionaries
      - cmake/latest/stable
    build-packages:
      - libxkbcommon-dev
      - libdrm-dev

    stage-packages:
      - libdrm2

    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr

    override-build: |
      craftctl default

      mkdir -p ${CRAFT_PART_INSTALL}/meta/gui
      cp ${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/256x256/apps/com.ktechpit.whatsie.png \
        ${CRAFT_PART_INSTALL}/meta/gui/icon.png

      sed -i \
        "s|^Icon=.*|Icon=\${SNAP}/meta/gui/icon.png|" \
        ${CRAFT_PART_INSTALL}/usr/share/applications/com.ktechpit.whatsie.desktop

    prime:
      - -usr/bug
      - -usr/doc
      - -usr/include
      - -usr/lib/*/cmake
      - -usr/share/ECM
      - -usr/share/man
      - -usr/share/lintian
